
name: Wahab Workflow
on: 
  push:
    branches:
      - staging 
jobs: 
  build: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print any file 
        run: cat README.md