
name: Wahab Workflow
on: 
  push:
    branches:
      - staging 
env: 
  APP_ENV: "dev"
jobs: 
  build: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        run: echo "AApp is conencito to $APP_ENV"